//Copyright 2008, 2009, 2010 Miguel Ángel Laguna Lobato
//
//This file is part of Multiclinical Trial Web-PACS.
//
//Multiclinical  Trial Web-PACS is free  software: you  can redistribute 
//it and/or modify it under  the terms of the GNU General Public License 
//as published by the Free  Software Foundation, either version 3 of the 
//License, or (at your option) any later version.
//
//Multiclinical  Trial Web-PACS is distributed  in the hope that it will 
//be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
//of  MERCHANTABILITY or  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
//General Public License for more details.
//
//You should have received a copy of the GNU General Public License
//along with Multiclinical Trial Web-PACS.  If not, see 
//<http://www.gnu.org/licenses/>.

package es.urjc.mctwp.modelo;

// Generated 28-may-2007 20:48:40 by Hibernate Tools 3.2.0.b9

/**
 * Participation generated by hbm2java
 */
public class Participation extends DomainObject implements java.io.Serializable {

	private static final long serialVersionUID = 7497785684615020090L;
	private User user;
	private Trial trial;
	private Rol rol;

	public Participation() {
	}
	
	public void setUser(User objUsuario) {
		this.user = objUsuario;
	}

	public User getUser() {
		return user;
	}

	public void setTrial(Trial objEnsayo) {
		this.trial = objEnsayo;
	}

	public Trial getTrial() {
		return trial;
	}
	
	public void setRol(Rol objRol) {
		this.rol = objRol;
	}

	public Rol getRol() {
		return rol;
	}

}
